sudo: required
env:
- APP_NAME=affinitytest
- AWS_ECR_ACCOUNT=973408325585
services:
- docker
install:
- docker build -t affinity .
- docker run -d --name affinity affinity
before_install:
- openssl aes-256-cbc -K $encrypted_0eded7138acf_key -iv $encrypted_0eded7138acf_iv
  -in .env.enc -out .env -d
script:
- docker exec affinity vendor/bin/phpunit
- docker stop affinity
- docker rm affinity
after_success:
- rm .env
- rm .env.enc
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-west-2)
- docker build -t $APP_NAME .
- docker tag $APP_NAME:$TRAVIS_BUILD_ID 973408325585.dkr.ecr.us-west-2.amazonaws.com/$APP_NAME:TRAVIS_BUILD_ID
- docker push $AWS_ECR_ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID

env:
  global:
    secure: dz7BVeUlV7YOx2OSyO6i7IURHkX+jvfIV6HoS9leXSCoYToQ1FrDFem6LjpM7nZXvbmAaLLmzLXvJtEjkR01mJIRKFjLi6Z/XhI6W5t5BesB5pfqjkzhVuvI9halmJxK/HEbY8biDoAl61spj3+s3CUeKZYGT9RbnaVqf3lFigxQvNKJHX3L3NvwafK+WCpB5E/4pJ8toMAtdQT0s1G36l0UtQCkHiRYTboXxRrdLyKPwp/yRDDxZ6854J3IIKs5qVtJjcHOcUopuPT5GGw4r0creYZ/GZtYQDGvrCnAXY4g9fHUMfZW4qifxEV2rKhyf31te+DZssb3NwENvy9bGX8I2mB6TUuOx92qbPw/0krQLU0f8mAvNEBTPbTYLEl9L88QSYCRLqrm5J50pxZuxvOrZJvZ79SZlcE2gOJw4YqmCDReRJ5OkxmG6RunAMD6sW8u0JVhU6fTUoEUObKGsyrNdLcrvrFWy7UIPeqhxeL8pr6HvVgLVyz7Cl801Uw3sM+3uXzHdo4EqecmP3iEoRsMxa+/W3QNGJQwJikefnCUrZ79q/E77ZJxZ+jWXTTnHu3zOzxbYnMvUfpdhm3z7+tzHa/FZ/DwiaazuShwLv63ZQlLThO3T9C2jjwli4anjerZvvd2hwDTGTMuHr9RXXae44t0xwHw74v097C+wOY=
