services:
- docker
install:
- docker build -t affinity .
- docker run -d --name affinity affinity
before_install:
- sudo apt-get install -y python3.4
- sudo apt-get install -y jq
- pip install awscli
- aws configure set aws_access_key_id $ACCESS_KEY_ID
- aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
- aws configure set default.region $DEPLOYMENT_REGION
- aws ssm get-parameters-by-path --region us-west-2 --with-decryption --path "/api/affinity/demo/" | jq -r '.Parameters[] | ([.Name, "\"" + .Value + "\""]) | join("=")' > /tmp/dev.affinity.ini
- sed -i~ 's#/api/affinity/demo/##' /tmp/dev.affinity.ini
- mv /tmp/dev.affinity.ini .env
script:
- docker exec affinity vendor/bin/phpunit
#- docker stop affinity
#- docker rm affinity
#after_success:
- rm .env
#- rm .env.enc
# This should be added to a script
#- pip install --user awscli
#- export PATH=$PATH:$HOME/.local/bin
#- eval $(aws ecr get-login --no-include-email --region us-west-2)
#- docker build -t affinity:v1.1 .
#- docker tag affinity:v1.1 973408325585.dkr.ecr.us-west-2.amazonaws.com/affinitytest:v1.1
#- docker push 973408325585.dkr.ecr.us-west-2.amazonaws.com/affinitytest:v1.1

env:
  global:
  - DEPLOYMENT_REGION=us-west-2
  - secure: dz7BVeUlV7YOx2OSyO6i7IURHkX+jvfIV6HoS9leXSCoYToQ1FrDFem6LjpM7nZXvbmAaLLmzLXvJtEjkR01mJIRKFjLi6Z/XhI6W5t5BesB5pfqjkzhVuvI9halmJxK/HEbY8biDoAl61spj3+s3CUeKZYGT9RbnaVqf3lFigxQvNKJHX3L3NvwafK+WCpB5E/4pJ8toMAtdQT0s1G36l0UtQCkHiRYTboXxRrdLyKPwp/yRDDxZ6854J3IIKs5qVtJjcHOcUopuPT5GGw4r0creYZ/GZtYQDGvrCnAXY4g9fHUMfZW4qifxEV2rKhyf31te+DZssb3NwENvy9bGX8I2mB6TUuOx92qbPw/0krQLU0f8mAvNEBTPbTYLEl9L88QSYCRLqrm5J50pxZuxvOrZJvZ79SZlcE2gOJw4YqmCDReRJ5OkxmG6RunAMD6sW8u0JVhU6fTUoEUObKGsyrNdLcrvrFWy7UIPeqhxeL8pr6HvVgLVyz7Cl801Uw3sM+3uXzHdo4EqecmP3iEoRsMxa+/W3QNGJQwJikefnCUrZ79q/E77ZJxZ+jWXTTnHu3zOzxbYnMvUfpdhm3z7+tzHa/FZ/DwiaazuShwLv63ZQlLThO3T9C2jjwli4anjerZvvd2hwDTGTMuHr9RXXae44t0xwHw74v097C+wOY=
