version: "3"

services:
  confd:
    build: ./confd
    volumes:
      - ~/.aws:/root/.aws
      - .:/var/www/html

  affinity:
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html

