version: "3"

services:
  confd:
    build: ./confd
    volumes:
      - ./target:/target
      - ~/.aws:/root/.aws
    environment:
      - AWS_PROFILE

  affinity:
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    environment:
      - AWS_PROFILE

  composer:
    restart: 'no'
    container_name: affinity_composer
    image: composer:latest
    command: install
    volumes:
      - .:/app/
